// Generated by typings
// Source: typings/custom/homeControllerScope/index.d.ts
declare interface IHomeControllerScope extends ng.IScope {
    departments: Department[];
    navigateToDepartment: (id: number) => void;
}
