// Generated by typings
// Source: typings/custom/localStorageService/index.d.ts
declare interface IApplicationLocalStorageService extends angular.localStorage.ILocalStorageService {
    employees: Employee[];
}
