// Generated by typings
// Source: typings/custom/departmentControllerScope/index.d.ts
declare interface IDepartmentControllerScope extends ng.IScope {
    employees: Employee[];
    addNew: () => void;
    removeEmployee: (employee: Employee) => void;
    resetEmployees: () => void;
    departmentName: string;
    maxAllowedEmployeesForDepartment: number;
}
